### ISSUE TITLE
Support for multiple VAs

### ISSUE THREAD

**Issue by anothergene** [Clamb94/StableApproach#54]
Allow for multiple VAs to be entered. Not sure how you would pick which one you are flying for for each flight though.

**Comment by Clamb94** [comment]
May I ask why you are active in multiple VAs? 
Depending on aircraft type or route you want to fly?

**Comment by anothergene** [comment]
No real reason, just two groups I want to support.  Probably a pretty low priority item, just thought I'd ask.

**Comment by Clamb94** [comment]
Sorry, this will not be implemented any time soon. Will close this issue for now

**Comment by anothergene** [comment]
No worries.   Thanks for taking the time to consider it.
