### ISSUE TITLE
Crash on saving reports

### ISSUE THREAD

**Issue by javaes** [Clamb94/StableApproach#58]
Hi, I'm using the latest Beta (1.4.0-beta.2) with XP12 on Linux.

After landing and leaving the runway the sim instantly freezes and I have to kill the process. At the same time my filesystem fills up quite quickly (I haven't figured out where it writes yet).

My last log line in the XP12 log.txt is:
`07:35:39.685073 StableApproach [DEBUG] Saving report: 194be6eb-34f4-4eea-91e5-f9fa6ff67826`

The report file exists, but has no content at all.

Please advise on how to provide better debug data.

**Comment by Clamb94** [comment]
Thank you very much for your report.

To be honest, I haven't tried the Linux and macOS versions myself, yet. 
When I'm back home next week, I'll try it myself on Linux and see what happens.

**Comment by Clamb94** [comment]
Found the issue.
Will be fixed with the next update, most likely to be released tomorrow.
Pleaser re-open this issue if the error still exists
