### ISSUE TITLE
Toliss flap position not recognized (X-Plane 12)

### ISSUE THREAD

**Issue by doitagainstudio** [Clamb94/StableApproach#60]
Hello all. On the Toliss the flap position is not recognized resulting in a persistent error with every flight i do.

**Comment by Clamb94** [comment]
Thanks for the info. Are you running a recent version of the toliss?
There have been a few updates to the Toliss aircraft (A319,A321,A346) which forced me to chage some datarefs

**Comment by FatihKoz** [comment]
With latest beta of Stable Approach and updated AircraftConfig files for ToLiSs aircraft, issue is fixed.

Tested with latest ToLiSs A321 (XP11/XP12 version)

**Comment by doitagainstudio** [comment]
Thx, I'm gonna download the new beta again and will check for it :-)
Regards

Cristiano Esposito

Il dom 8 gen 2023, 19:15 B.Fatih KOZ ***@***.***> ha scritto:

**Comment by Clamb94** [comment]
No need to download it again, it will update itself.
I'll close this issue for now. If you still have this problem, feel free to re-open it
